posit-dev/pointblank

pointblank/__init__.py, pointblank/_interrogation.py, pointblank/_utils_check_args.py, pointblank/column.py, pointblank/validate.py, tests/test__interrogation.py, tests/test_column.py, tests/test_validate.py
For some of the row-based validations, it makes sense to be able to compare across two (or more) columns instead of comparing only to fixed values. For example, with `col_vals_gt()`, you could perform a validation that checks whether values in a column are greater than `5`:
```python
pb.Validate(tbl).col_vals_gt(columns="x", value=5).interrogate()
```
But it can often be the case that you want to verify whether values in the `x` column are greater than values in an adjacent column (`y`), like this:
```python
pb.Validate(tbl).col_vals_gt(columns="x", value=pb.col("y")).interrogate()
``` 
This PR implements the `col()` function and allows it to work in these types of validations:
- `col_vals_gt()`
- `col_vals_lt()`
- `col_vals_ge()`
- `col_vals_le()`
- `col_vals_eq()`
- `col_vals_ne()`
- …
=> Implement use of column expressions for certain validation types for nw-backend tables

.github/workflows/ci-docs.yaml, .github/workflows/ci-tests.yaml, pyproject.toml
This removes the ibis dependency but allows for installs by supported ibis backend (and also has optional installs for Pandas and Polars). Uses `[dependency-groups]` instead of `[project.optional-dependencies]` in `pyproject.toml` as recommended in #1 .
Fixes #1
=> Reduce dependencies; split into dependency groups

pointblank/validate.py, tests/test_validate.py
Some of the validation methods that let you extract pieces of reporting information from a `Validation` object (post-interrogation) have an `i=` argument that let you constrain the collection to certain steps. If providing a scalar integer to `i=` it would be convenient to forego the dictionary structure and just obtain the value or DataFrame (for the `get_data_extracts()` method). This PR adds the `scalar=` or `frame=` arg (the latter for `get_data_extracts()`). If `True` (default is `False`) and `i=` is a scalar value, then this type of return is provided.
=> feat: add `scalar=`/`frame=` arg to several Validate methods

docs/_quarto.yml, docs/get-started/thresholds.qmd, pointblank/__init__.py, pointblank/column.py, pointblank/validate.py, tests/test_validate.py
This adds a function to set global config options for pointblank. Here, two options are provided: `report_incl_header` and `report_incl_footer`.
=> Add global config options for validation table output

pointblank/validate.py
This adds the `Column` type to `value=`/`left=`/`right=` args in several validation methods.
=> Add `Column` type to `value=`/`left=`/`right=`

pointblank/_interrogation.py, pointblank/schema.py, pointblank/validate.py, tests/test_validate.py
This PR adds the `case_sensitive_colnames=` and `case_sensitive_dtypes=` arguments to the `col_schema_match()` validation method. Both are set to `True` by default, which doesn't change the previous behavior. Setting any of these to `False` performs a case-insensitive match during interrogation.
The most important changes include updates to the `ColSchemaMatch` class, the schema comparison methods, and the `col_schema_match()` method, as well as new test cases to ensure the correctness of these features.
Enhancements to schema matching:
* [`pointblank/_interrogation.py`]: Added `case_sensitive_colnames` and `case_sensitive_dtypes` parameters to the `ColSchemaMatch` class and updated the `__post_init__` method to handle these parameters.
Updates to schema comparison methods:
* …
=> feat: add options for case-insensitive matching of coltypes and dtypes in schema checks

pointblank/validate.py, tests/snapshots/test_validate/test_no_steps_validation_report_html_snap/no_steps_validation_report.html, tests/test_validate.py
This PR introduces several changes to handle scenarios where there are no validation steps in a validation plan. The main changes include updates to the `get_tabular_report()` method, new test cases, and corresponding HTML snapshot updates.
Handling no validation steps:
* [`pointblank/validate.py`]: Added logic to handle cases where there are no validation steps, including creating a message and an empty table with appropriate formatting.
Test cases:
* [`tests/test_validate.py`]: Added a new test `test_no_steps_validation_report_html_snap` to validate the HTML report output when there are no validation steps.
* [`tests/test_validate.py`]: Added a new test `test_validation_report_json_no_steps` to check the JSON report output when there are no validation steps.
HTML snapshots:
* …
=> fix: display empty validation reports when there are no validation steps

pointblank/_interrogation.py, pointblank/schema.py, pointblank/validate.py, tests/test_validate.py
This PR introduces the ability to perform substring matching on dtypes during schema validation (using `col_schema_match()`). The changes include updates to the schema validation logic, the addition of a new parameter `full_match_dytpes=` (default is `True`), and corresponding updates to the test cases.
=> feat: partial matching for dtypes

pointblank/schema.py, tests/test_schema.py, tests/test_validate.py
This pull request includes changes to the `Schema` class in the `pointblank/schema.py` file, enhancing its flexibility and functionality. The most important changes include updating the schema definition and validation methods, modifying the `_process_columns()` function, and adding new tests to ensure the correctness of the new functionality.
Enhancements to schema definition and validation:
* [`pointblank/schema.py`]: Updated the `Schema` class to support various ways of defining schemas, including lists of column names, tuples, and dictionaries. Improved the documentation to reflect these changes.
* [`pointblank/schema.py`]: Modified the `columns=` attribute to accept strings, lists of strings, lists of tuples, or `None`.
Functionality improvements:
* [`pointblank/schema.py`]: Enhanced …
=> feat: within `col_schema_match()`, enable checks of columns only (exclusive of dtypes)

pointblank/_interrogation.py, pointblank/schema.py, pointblank/validate.py, tests/test_validate.py
This PR enhances the `Schema` class so that multiple column data types can be declared. This doesn't affect previous tests or potential workflows since a dtype can be provided as a string value (previously) or list of strings (new here). Many new tests added to verify the new functionality.
We also fix an argument typo across multiple files (the `full_match_dtypes=` arg) and update/improve the clarity of the `schema` documentation.
Typographical error fixes:
* Corrected the spelling of `full_match_dtypes=` in `pointblank/_interrogation.py`, `pointblank/schema.py`, and `pointblank/validate.py` files.
Documentation improvements:
* Enhanced the schema documentation in `pointblank/schema.py` to clarify the format for specifying column names and data types.
Regex pattern refinements:
* Updated …
=> feat: allow definition of multiple dtypes per column in `Schema` to facilitate multiple attempts at dtype matching

docs/_quarto.yml, pointblank/_utils_check_args.py, pointblank/validate.py, tests/snapshots/test_validate/test_validation_with_selector_helper_functions_no_match_snap/tbl_memtable_variable_names/selector_helper_functions_no_match.html, tests/snapshots/test_validate/test_validation_with_selector_helper_functions_no_match_snap/tbl_pd_variable_names/selector_helper_functions_no_match.html, tests/snapshots/test_validate/test_validation_with_selector_helper_functions_no_match_snap/tbl_pl_variable_names/selector_helper_functions_no_match.html, tests/test__utils_check_args.py, tests/test_validate.py
This PR focuses on enhancing the `col_vals_*` validation methods to accept `Column` objects, which allows for more dynamic and flexible column comparisons.
Updated the `col_vals_gt()`, `col_vals_lt()`, `col_vals_eq()`, `col_vals_ne()`, `col_vals_ge()`, `col_vals_le()`, `col_vals_between()`, etc., etc., validation methods to accept `Column` objects (through `col()`) in `columns=` argument. This includes changes to parameter documentation and the addition of logic to handle `Column` objects appropriately. This is lazy, in that resolution of the columns by column selectors isn't performed until the `interrogate()` method is called.
Also added the `eval_error` attribute to the `_ValidationInfo` class to track evaluation errors (e.g., column selectors not resolving to any columns. This …
=> feat: column selectors for defining columns in validation workflow

pointblank/preview.py
This PR, focused on improving the table preview functionality, adds the `show_row_numbers=` parameter so that row numbers can be displayed in the output. The `preview()` function has also been refactored here to improve readability, with better variable naming and restructuring logic for handling columns and data types.
=> feat: add row numbers to preview

pointblank/preview.py, pointblank/validate.py
This PR improves the preview functionality and handling of table metadata. A new `incl_header=` arg has been added to `preview()`, allowing for an info header to be shown. 
Additionally, missing values are now highlighted in the table with added logic to identify and highlight `None`, `NA`, and `NULL` values in the table preview.
=> feat: add option for info header in `preview()` table

docs/_quarto.yml, pointblank/__init__.py, pointblank/preview.py, tests/test_preview.py
This PR introduces new functions for obtaining the column (`get_column_count()`) and row (`get_row_count()`) counts of tables. There are also updates to the relevant documentation and new tests.
=> feat: add the `get_column_count()` and `get_row_count()` functions

pointblank/_constants.py, pointblank/validate.py, tests/snapshots/test_validate/test_validation_report_interrogate_snap/tbl_duckdb/validation_report.json, tests/snapshots/test_validate/test_validation_report_interrogate_snap/tbl_parquet/validation_report.json, tests/snapshots/test_validate/test_validation_report_interrogate_snap/tbl_pd/validation_report.json, tests/snapshots/test_validate/test_validation_report_interrogate_snap/tbl_pl/validation_report.json, tests/snapshots/test_validate/test_validation_report_interrogate_snap/tbl_sqlite/validation_report.json, tests/snapshots/test_validate/test_validation_report_no_interrogate_snap/tbl_duckdb/validation_report.json, tests/snapshots/test_validate/test_validation_report_no_interrogate_snap/tbl_parquet/validation_report.json, tests/snapshots/test_validate/test_validation_report_no_interrogate_snap/tbl_pd/validation_report.json, tests/snapshots/test_validate/test_validation_report_no_interrogate_snap/tbl_pl/validation_report.json, tests/snapshots/test_validate/test_validation_report_no_interrogate_snap/tbl_sqlite/validation_report.json, tests/snapshots/test_validate/test_validation_report_use_fields_snap/tbl_duckdb/validation_report.json, tests/snapshots/test_validate/test_validation_report_use_fields_snap/tbl_parquet/validation_report.json, tests/snapshots/test_validate/test_validation_report_use_fields_snap/tbl_pd/validation_report.json, tests/snapshots/test_validate/test_validation_report_use_fields_snap/tbl_pl/validation_report.json, tests/snapshots/test_validate/test_validation_report_use_fields_snap/tbl_sqlite/validation_report.json, tests/test_validate.py
When defining validation steps, the approach is be completely lazy and not access the target table (only doing so when `interrogate()` is called). Owing to this, a single definition of a step can result in a single actual validation step, or, multiple (e.g., when using column selector functions or when providing a list of columns for applying the check).
To track this better, the PR uses the `i_o` attr to store step numbers before interrogation (i.e., each call of a validation method will increment this value) and the `i` value will be the actual sequence of validation steps (determined at interrogation time). The tabular report view uses the `i` value; in the case where the tabular report shows the validation plan w/o interrogation, the `i_o` index values will be used.
=> fix: make corrections to step indexing

pointblank/validate.py, tests/snapshots/test_validate/test_comprehensive_validation_report_html_snap/comprehensive_validation_report.html, tests/test_validate.py
This PR improves the display of text in a validation report table containing `rows_distinct()` validation steps. Previously the `COLUMNS` and `VALUES` columns had unformatted values in those fields (e.g., `"None"`) but this PR provides descriptive labels.
=> fix: improve visual display of `rows_distinct()` steps in validation report

pointblank/validate.py
This PR simply makes a deep copy of the input data table in the `preview()` function to avoid modifying the data globally.
=> fix: in `preview()` function, make a copy of the input table

pointblank/schema.py, tests/test_schema.py
This fixes an issue in the `Schema` class (resulting in an expectation problem when using the `col_schema_match()` validation method) where the target table was converted to a Narwhals DataFrame prior to extracting information about the table's schema. This has been revised to remove that conversion and to perform schema collection for Polars and Pandas DataFrames.
Fixes: https://github.com/rich-iannone/pointblank/issues/39
=> fix: when collecting target table schema, avoid conversion to Narwhals (use native DF schemas)

pointblank/_utils.py, tests/test__utils.py
This adds the internal functions: `_get_api_text()`, `_get_examples_text()`, and `_get_api_and_examples_text()`. For the first, the docstrings from exported classes, functions, and methods are combined into a single string. With `_get_examples_text()`, code from the project website's examples page is condensed into a string. The last function, `_get_api_and_examples_text()` provides both in a single string.
=> feat: add internal functions to get condensed API docs and examples text

pointblank/validate.py
A recent update of Ibis breaks the `preview()` function when it is used with Ibis backend tables. The issue was in the use of the `head()` method and explicitly providing the `n` arg name. This change removes that and `preview()` should no longer error.
Fixes: https://github.com/posit-dev/pointblank/issues/51
=> fix: remove arg name usage in Ibis .head() method call

data_raw/x-02-duckdb.qmd, pointblank/validate.py, tests/test_validate.py
This PR adds the `nycflights` dataset to the package. It can be loaded via `load_dataset()`. Tests have been updated to account for this new dataset. The dataset is also used in an example for the `missing_vals_tbl()` function.
=> feat: add the `nycflights` dataset

docs/_quarto.yml, pointblank/validate.py, tests/test_validate.py
I'm using this package in my professional life and find myself (and my teammates) frequently writing boilerplate to wrap the `all_passing` method to check if tests pass. I think a `assert_passing` method would be beneficial for 2 reasons:
1. It's simply less code than `assert v.all_passing(), msg`, especially when the message is standard and contains no special information to be surfaced. I'll admit it's nearly identical but I personally find it nice.
2. In the case where the message is more involved, having the message be generated by by the instance could save quite a bit of code. For example, if I need to surface what tests actually failed via the AssertionError's message, it would be nice to have it built in. However, I did not implement this, as it's only an idea, but I'd be happy to …
=> Add Explicit Assertion Method to `Validate` for Test Suites

docs/_quarto.yml, pointblank/__init__.py, pointblank/thresholds.py, pointblank/validate.py, tests/test_thresholds.py, tests/test_validate.py
This adds the `Actions` class and integration of actions in the `Validate` class, many validation methods that contain a `thresholds=` arg, and the `interrogate()` method. Providing input to `actions=` operates similarly to input provided to `thresholds=` (e.g., having local and global scope, with preference to local actions provided in validation methods). For now, the `Actions` parameters can accept a string (where the action is printing to the console) or a callable (which is executed). These are executed stepwise at interrogation time.
=> feat: Add ability to execute actions based on entering threshold levels

Makefile, pointblank/_interrogation.py, pointblank/_typing.py, pointblank/_utils.py, pointblank/validate.py, pyproject.toml, tests/test_validate.py
I added a tolerance to the row count match validation. It is useful for source data that is updating constantly or very large, ie. big time streaming data. I want the ability to allow for some tolerance.
=> Add tolerance to row count match

pointblank/validate.py, tests/test_validate.py
This is a piggy back on my `assert_passing` commit. It should have at least some information about what actually failed. I have mixed feelings putting this information in the AssertionError message itself but it's not uncommon, and would only produce issues if there were huge autobriefs or interrogations.
=> Make assert_passing method indicate which tests failed

pointblank/thresholds.py, pointblank/validate.py, tests/test_validate.py
This PR adds the ability to use templating variables for strings passed to the `brief=` argument, available in all validation methods. If using a string as a value when calling `Actions`, that string could use an expanded set of templating variables (six in total). Documentation has been added to explain which vars can be used for `brief=` and within `Actions`.
=> feat: templating for `brief` and `Actions` text

pointblank/datascan.py
This PR cleans up the appearance of the report table generated by `col_summary_tbl()`. For string-based columns, the report table indicates those cells where values are based on string lengths. We also only include only the `min`, `median`, and `max` string length quartile stats.
=> feat: improve appearance of `col_summary_tbl()` report table

pointblank/_constants.py, pyproject.toml
This PR enables  Databricks and PySpark support through Ibis.
=> fix: enable Databricks and PySpark support

README.md
Thank you for contributing to pointblank! To make this process easier for everyone, please explain the context and purpose of your contribution. Also, list the changes made to the existing code or documentation.
- Ref: #
=> About validation report from the REPL

pointblank/_constants.py
A follow up PR to improve MS SQL Server support. Adds table type styling based on pointblank R style for MSSQL.
- Ref: #95
- [ x ] I understand and agree to the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/).
- [ x ] I have followed the [Style Guide for Python Code](https://peps.python.org/pep-0008/) as best as possible for the submitted code.
=> Add mssql style to TABLE_TYPE_STYLES

pointblank/_constants.py, pointblank/validate.py, tests/test_validate.py
This makes it somewhat easier to put together column-to-column validations with dates/datetimes. Now, this works with several of the validation methods. A series of followup PRs will make it work with comparisons against a static date or datetime, but this particular PR solves https://github.com/posit-dev/pointblank/issues/106.
Fixes: https://github.com/posit-dev/pointblank/issues/106
=> fix: allow validations to work with dates/datetimes

pointblank/validate.py
This PR adds the `min_tbl_width=` arg to the `preview()` function. Previously, very narrow tables would truncate information in the `preview()` table's header area. The new parameter adds width equally to each of the columns in those situations where the total width is below the threshold. The default of `500px` provides ample space for the table header to display its information about the table.
=> feat: Add the `min_tbl_width=` arg in `preview()` to improve display of narrow preview tables

pointblank/validate.py, tests/test_validate.py
Because tables can have a lot of columns, it could make a step report (based on `col_vals_*()` steps) quite unwieldy without subsetting. To make this type of reporting more customizable, this PR includes a `columns_subset=` parameter. Users could choose with columns to include with the target column using the same subsetting interface as in the `preview()` function (which also has a `columns_subset=` arg.
Here's how it looks in practice:
```python
import pointblank as pb
validation = (
pb.Validate(data=pb.load_dataset(dataset="game_revenue", tbl_type="polars"))
.col_vals_lt(columns="item_revenue", value=200)
.col_vals_gt(columns="item_revenue", value=0)
.col_vals_gt(columns="session_duration", value=5)
.col_vals_in_set(columns="item_type", set=["iap", "ad"]) …
```
=> feat: add ability to select subset of columns in row-based step reports

pointblank/thresholds.py, tests/test_validate.py
This PR adds the `default=` parameter to the `Actions` class. This is helpful in that a common callable or string (or list of various strings/callables) only needs to be set once to be a trigger for all three threshold levels.
=> feat: add `default=` parameter to `Actions`

pointblank/validate.py, tests/snapshots/test_validate/test_validation_report_briefs_global_local_html/validation_report_briefs_global_local.html, tests/test_validate.py
This PR adds the ability to set a global `brief=` value when using the `Validate` class. The `brief=` parameters in the various validation methods can always override the globally set value.
=> feat: add global setting option for `brief=`

pointblank/data/api-docs.txt, pointblank/validate.py, tests/test_validate.py
This PR is a fix for the unbounded collection of extract rows. There was a limit arg in `interrogate()` but it only applied to extracts collected via sampling (not the default). This change ensures that the limit is applied universally.
Fixes: https://github.com/posit-dev/pointblank/issues/129
=> fix: set limit on extracts no matter which scheme was used for collection

pointblank/_interrogation.py, tests/test_validate.py
This PR introduces flexibility in date/datetime validation checks. With a date column, you can set the `value=` in a `col_vals_*()` method to a date or a datetime (the latter will be internally transformed to use a floor date). Same flexibility is present for a datetime column, where you can use a datetime or a date as input (the date is transformed to a datetime with the time part being `00:00:00`).
=> feat: flexible date/datetime comparisons

pointblank/validate.py, tests/test_validate.py
In previous PRs, we opened up the possibility to use `datetime.date` and `datetime.datetime` objects for the `value=` parameter in several validation methods (e.g., `col_vals_gt()`, `col_vals_between()`, etc.). So long as the columns are date or datetime columns, the validation will proceed as expected during interrogation.
This PR makes it so that the date or datetime input provided to `value=` can be a string-based date or datetime. The major requirement is that the string date or datetime must follow ISO-8601 formatting guidelines. With this, the following example now works:
```python
import pointblank as pb
import polars as pl
pl_df = pl.DataFrame(
{
"date_1": ["2021-01-01", "2021-02-01"],
"date_2": ["2021-02-01", "2021-03-01"],
"dttm_1": ["2021-01-01 02:30:00", "2021-02-01 …
```
=> feat: allow date/datetime comparison validations to use string dates and datetimes 

pointblank/validate.py
This PR provides more documentation on several common args in the validation workflow: `thresholds=`, `actions=`, `lang=`, `value=`, and `pre=`.
=> docs: enhance docs for `Validate` and the validation methods

pointblank/validate.py
This PR localizes the numeric values for the thresholds summary (fractions between 0-1 and integer values) in the validation report table. With this the `lang`/`locale` values provided to `Validate` are used, matching the formatted values elsewhere in the report.
=> fix: localize threshold HTML text through formatting

pointblank/data/api-docs.txt, pointblank/validate.py, tests/snapshots/test_validate/test_comprehensive_validation_report_html_snap/comprehensive_validation_report.html, tests/snapshots/test_validate/test_no_interrogation_validation_report_html_snap/no_interrogation_validation_report.html, tests/snapshots/test_validate/test_no_steps_validation_report_html_snap/no_steps_validation_report.html, tests/snapshots/test_validate/test_validation_report_briefs_global_local_html/validation_report_briefs_global_local.html, tests/snapshots/test_validate/test_validation_report_briefs_html/validation_report_with_briefs.html, tests/snapshots/test_validate/test_validation_with_selector_helper_functions_no_match_snap/tbl_memtable_variable_names/selector_helper_functions_no_match.html, tests/snapshots/test_validate/test_validation_with_selector_helper_functions_no_match_snap/tbl_pd_variable_names/selector_helper_functions_no_match.html, tests/snapshots/test_validate/test_validation_with_selector_helper_functions_no_match_snap/tbl_pl_variable_names/selector_helper_functions_no_match.html
Awhile back, threshold levels were renamed to align with log levels. This PR completes the process by renaming internal variable to completely match the user-facing names. Also, some stale documentation on thresholds (including some older naming) is revised here.
=> fix: rename internal references to threshold levels

pointblank/validate.py, tests/test_validate.py
This PR makes a second attempt to better let the user customize the header in a step report. Previously, the `header=` arg would accept text that would completely replace the header. However, the header in a step report consists of a title element and a larger details element. You couldn't replace only the title portion without wiping out the details part in the process.
Here, we allow for use of templating, where the default template is `"{title}{details}"` (and `header=":default:"` calls up this standard template). If you wanted to replace the title and keep the details, you'd supply `"Custom Title {details}"`. Here's an example:
```python
import pointblank as pb
validation = (
pb.Validate(data=pb.load_dataset(dataset="game_revenue", tbl_type="polars")) …
```
=> feat: better customize header in step reports (through `.get_step_report(header=...)`

docs/_quarto.yml, pointblank/__init__.py, pointblank/thresholds.py, pointblank/validate.py, tests/test_validate.py
This PR introduces the `FinalActions` class and integrates it into the `Validate` workflow. It'll allow users to define actions that execute after all validation steps have completed. The key changes here:
- added the `FinalActions` class for wrapping strings, callables, or lists of actions (similar to the `Actions` class)
- enhanced the `Validate` class to accept a `final_actions=` parameter
- implemented the `_execute_final_actions()` method in `Validate` to run final actions after interrogation
- added the `_get_highest_severity_level()` method to determine overall validation status
- created a context manager system for providing summary data to final actions
- added documentation and tests
Here's an example of how it works:
```python
import pointblank as pb
def send_alert():
summary …
```
=> feat: add ability to execute final actions for validation (post-interrogation actions)

pointblank/_interrogation.py, pointblank/validate.py, tests/test_validate.py
This PR would close #161 . It simply allows for `None` values for `col_vals_in_set`. I have some basic testing done for it, any more cases you think I should cover, always like another eye on tests.
Also, I widened the types allowed for the `set` arg to `Collection[Any]`, which is how Narwhals (and Polars) types it. Ibis types it as `Sequence[Any]`, which is also fine but I personally believe it's too narrow, and potentially misleading. `Sequence` classes need to implement methods we surely don't care about like`__getitem__` and `reversed()`. I actually commonly pass immutables like tuples, or custom classes to these things so the ability to pass any generic collection is quite helpful.
=> Allow `None` in `col_vals_in_set`

.github/workflows/ci-tests.yaml, Makefile, pointblank/validate.py, pyproject.toml, tests/test__utils.py, tests/test_validate.py
This pr will close #164 . There's 1 change to the source code - when a duckdb dataset is loaded, it's extracted to a temporary directory and not source folder in site packages. 
Moving to tmp before connecting also has the effect of removing the need for write permissions to your source code location. For example if users have their environment sitting on a shared location, loading a duckdb dataset should(?) fail since they could not extract it. I'm also unsure of duckdb's file locking rules on this, they seem to handle connecting to a file differently than the other libraries. I'm also fairly certain Ibis is the one checking for locked files on behalf of duckdb. I'm not familiar with the Ibis library enough to hypothesize the mechanism.
In summary, serializing the loading of example …
=> Parallel and randomly ordered tests

docs/user-guide/briefs.qmd, pointblank/validate.py, tests/test_validate.py
This PR adds templating variables for the `brief=` such that the step value, thresholds, and segments can be included in the processed text.
The User Guide article on briefs has also been updated to account for the increased set of templating variables.
=> feat: segment brief variables

pointblank/schema.py, tests/test_schema.py
This fix will make printed schemas work even if there is no type declared for a column.
=> fix: improve schema as str when type not declared

pointblank/validate.py, tests/test_validate.py
This PR is a minor update to the `assert_passing()` method. It provides some convenience by executing `.interrogate()` on `Validate` objects that haven't been interrogated. And interrogated `Validate` continue to work as they did before with `assert_passing()`.
=> feat: allow `assert_passing()` to interrogate when needed

docs/_quarto.yml, pointblank/validate.py, tests/test_validate.py
This PR adds the new `assert_below_threshold()` method to the `Validate` class. This method allows users to programmatically verify that validation failures remain below specified threshold levels ('warning', 'error', or 'critical').
Things it does:
- raises an AssertionError if any validation step exceeds the specified threshold level
- supports checking specific validation steps via the i parameter
- auto-interrogates data if validation hasn't been performed yet
- allows custom error messages
- returns validation step details in the error message (for easier debugging)
- integrates with the existing threshold system ('warning', 'error', 'critical')
This method is useful in automated testing environments where you want to ensure your data quality meets minimum standards before …
=> Feat assert below threshold

docs/user-guide/installation.qmd, pointblank/_constants.py, pyproject.toml
This adds basic support for Ibis-backend BigQuery tables. As a follow-up task, BigQuery tables need to be manually tested to determine if there are any API-related issues with these tables. 
Fixes: https://github.com/posit-dev/pointblank/issues/187
=> feat: add BigQuery support

pointblank/actions.py, pointblank/column.py, pointblank/data/api-docs.txt, pointblank/thresholds.py, pyproject.toml
This PR replaces instances of `\d` in docstrings with `[0-9]` in code involving regexes (and the replacement is good enough for the examples). This helps to avoid several `SyntaxWarning`s with the message: `"invalid escape sequence '\d'"`.
=> fix: remove all invalid escape sequences in docstrings

pointblank/validate.py, tests/test_validate.py
This pull request enhances the `Validate` class to support CSV file inputs directly, allowing users to validate data stored in CSV files without manually loading them. It also introduces automated library selection for CSV parsing (Polars preferred, Pandas as fallback).
=> feat: add ability to directly use CSV data as `Validate` inputs

docs/_quarto.yml, pointblank/__init__.py, pointblank/validate.py, tests/test_validate.py
This PR expands the data input capabilities of the `Validate` class by allowing the use of database connection strings. Users can now pass in a connection string like `"postgresql://user:pass@host/db::table_name"` to the `data=` parameter. The implementation also adds the `connect_to_table()` utility for DB table connections.
=> feat: data path strings

docs/styles.css
This PR changes the overflow style for `dt` from scroll to visible to avoid the scrollbar obscuring the API docs on Windows.
Fixes: https://github.com/posit-dev/pointblank/issues/211
=> docs: update scrollbar style

pointblank/assistant.py, pointblank/cli.py, pointblank/compare.py, pointblank/datascan.py, pointblank/validate.py, tests/test_validate.py
This PR adds the `_process_data()` utility function, which is used by classes or functions that ingest data.
=> fix: use `_process_data()` to centralize data ingest functionality

pointblank/cli.py, tests/test_cli.py
This PR removes the `extract` command from the CLI and its associated functionality, tests, and references in the codebase. Extraction of failed rows is now handled consistently in `validate` and `validate-simple`. We also now have a `--write-extract PATH` command to write failed rows as a CSV.
=> fix: simplify extracts in CLI utility

pointblank/cli.py
This PR improves the message that appears when using only `pb validate <data>`.  It also adds a `--list-checks` option to display the available validation checks (along with descriptions).
=> fix: improve messages with `pb validate <data>` default; add `--list-checks` option

pointblank/cli.py
This PR allows any required column selection in `pb validate` to use `#N` notation following `--column`. This specifies a column by index.
=> enh: for `pb validate` allow `--column` to use column index

pointblank/cli.py
This PR distinguishes between rows displayed in the console and rows saved to CSV files (for `pb validate` and `pb run`). The display limit is now consistently set to 10 rows, while the save limit defaults to 500 rows.
=> fix: use CLI limit for extract CSVs only

pointblank/cli.py
This PR updates the `pointblank` CLI to support YAML configuration files in addition to Python scripts for data validation (in `pb run`). Now users can define validation steps declaratively in YAML, while maintaining Python script functionality in the CLI. 
The `pb make-template` command can now also generate YAML configuration templates, with examples for validation rules, data sources, and thresholds. The template type is determined by the file extension (`.py` for Python scripts, `.yaml/.yml` for YAML configs).
Help messages and examples were also updated to reflect the new YAML file functionality.
=> feat: allow Pointblank CLI to run YAML validation via `pb run`

pointblank/validate.py, pyproject.toml
closes #250 
The minimum Narwhals in pointblank is 1.41 but `ignore_nulls=True` was only introduced in Narwhals 1.45.
I'd suggest:
- either, handling all Narwhals versions with an if-else block
- or (better, IMO) bump the minimum version to 1.45
Thank you for contributing to Pointblank! To make this process easier for everyone, please explain the context and purpose of your contribution. Also, list the changes made to the existing code or documentation.
- Ref: #
=> fix: specify `ignore_nulls=True` in `nw.all_horizontal`

.github/workflows/ci-tests.yaml, pointblank/_constants.py, pointblank/_interrogation.py, pointblank/_utils.py, pointblank/assistant.py, pointblank/data/api-docs.txt, pointblank/schema.py, pointblank/validate.py, pyproject.toml, tests/snapshots/test_validate/test_comprehensive_validation_report_html_snap/comprehensive_validation_report.html, tests/snapshots/test_validate/test_validation_report_interrogate_snap/tbl_pyspark/validation_report.json, tests/snapshots/test_validate/test_validation_report_no_interrogate_snap/tbl_pyspark/validation_report.json, tests/snapshots/test_validate/test_validation_report_use_fields_snap/tbl_pyspark/validation_report.json, tests/test_validate.py
This pull request adds support for PySpark DataFrames throughout the codebase, improving compatibility and handling for PySpark in schema detection, validation, and DataFrame interrogation. It introduces a new utility for safely handling datetime comparisons across DataFrame types (esp. for LazyFrames), and refactors several functions to use this new utility. Additionally, it updates the CI workflow to ensure Java is available for PySpark tests.
I modified CI workflow to set up Java (using Temurin 11) for PySpark tests and optimized PySpark memory settings for the CI environment. If PySpark tests end up becoming flaky in CI, we can temporarily disable them by setting:
```yaml
env:
SKIP_PYSPARK_TESTS: "true"
```
Fixes: https://github.com/posit-dev/pointblank/issues/253
=> feat: validate Spark DFs without using Ibis

docs/_quarto.yml, docs/user-guide/yaml-reference.qmd, docs/user-guide/yaml-validation-workflows.qmd, pointblank/data/api-docs.txt, pointblank/validate.py, pointblank/yaml.py, tests/test_validate.py, tests/test_yaml.py
This PR adds the `set_tbl()` method for `Validate` objects and also adds `set_tbl=` parameter to the `yaml_interrogate()` function. This provides extra flexibility in reusing existing validation rules with different yet compatible tables.
Fixes: https://github.com/posit-dev/pointblank/issues/259
=> feat: Add the `set_tbl()` method and add `set_tbl=` to `yaml_interrogate()`

pyproject.toml
This PR updates the `duckdb` dependency version constraint in the development dependencies to avoid compatibility issues with versions `1.4.0` and above. We now require versions `>=1.2.0` and `<1.3.3`. Added a comment explaining that this pinning to stable versions avoids `RecordBatchReader` issues present in `1.4.0` and later.
=> ci: pin `duckdb` dependency to stable versions

pointblank/validate.py, tests/test_validate.py
This adds direct support for using Enums in the `col_vals_in_set()` and `col_vals_not_in_set()` validation methods.
Fixes: https://github.com/posit-dev/pointblank/issues/153
=> feat: add Enum support to `col_vals_in_set()` and `col_vals_not_in_set()`
