pyproject.toml

This fixes up a problem in #4 where dependency groups were added, but no optional dependencies were made. This adds in the optional dependencies.

fix: add optional dependencies

---

pointblank/validate.py

This PR adds in examples for the validation methods (e.g., `col_vals_gt()`, etc.).

Add examples for validation methods

---

pointblank/_utils_check_args.py
pointblank/column.py
pointblank/validate.py
tests/test_column.py
tests/test_validate.py

This PR introduces the `ColumnSelector` class to enhance column selection capabilities. The changes include updating various validation functions to support `ColumnSelector`, and adding corresponding tests to ensure the new functionality works correctly. Missing documentation was also added for all of the column selector functions.

feat: add `ColumnSelector` class and improve documentation for all column selector functions

---

docs/_quarto.yml
docs/examples/index.qmd

This PR adds an examples page to the docs site.

docs: add Examples page

---

CONTRIBUTING.md

This PR updates the dev install instructions, which fail for me in zsh. This works and follows the pattern in the GH Actions script

.[dev] -> '.[dev]'

---

pointblank/column.py
pointblank/draft.py
pointblank/schema.py
pointblank/thresholds.py
pointblank/validate.py

This PR adds interlinks to navigate between reference API pages.

docs: add interlinks throughout reference API pages

---

pointblank/_constants.py
pointblank/draft.py

add bedrock

---

pointblank/data/api-docs.txt
pointblank/datascan.py
tests/test_datascan.py

This PR contains an extensive refactor of the `DataScan` class. We include measures of missingness and distinctness for all columns. For numerical columns, measures of negative, zero, and positive values are now added. Float values are rounded with sensible limits, and fractional values (between `0` and `1`) are rounded to three significant digits.

feat: improve DataScan

---

.github/workflows/code-checks.yaml
.pre-commit-config.yaml
tests/test_schema.py

This PR adds a workflow (`Code Checks`) to run `pre-commit` in CI.

ci: add `Code Checks` CI workflow

---

pointblank/_constants.py
pyproject.toml

This PR enables snowflake support through Ibis.

fix: enable snowflake support

---

pointblank/_utils.py
pointblank/data/api-docs.txt

The internal `get_api_text()` function was not up-to-date with the current API. This PR updates that function and also updates the `api-docs.txt` file.

fix: update `get_api_text()`

---

pointblank/_constants.py
pointblank/_constants_translations.py
pointblank/validate.py

This PR adds the Hindi translation so that briefs and the validation report table can be displayed in that language.

feat: add Hindi translation

---

pointblank/_constants.py
pointblank/_constants_translations.py
pointblank/validate.py

This PR adds the Greek translation so that briefs and the validation report table can be displayed in that language.

feat: add Greek translations

---

.github/workflows/ci-docs.yaml

This PR adds a netlify preview deployment to this repo

ci: add netlify docs preview

---

.github/workflows/ci-docs.yaml

ci: build docs in PRs

---

docs/scripts/post-render.py

This PR is for making a few more improvements to the API reference section of the docs site.

docs: make further changes on the API reference pages

---

docs/scripts/post-render.py
docs/styles.css

This PR is for making more changes to the site's API reference pages.

docs: make further modifications of API reference pages

---

pointblank/validate.py
tests/test_validate.py

This PR adds tests for lines in the `pointblank/validate.py` file.

fix: add more tests for `validate.py` file

---

pointblank/cli.py

This PR is focused on ensuring that tables generated through the CLI utility have a consistent display of information.

fix: improve display of tables in CLI utility

---

pointblank/cli.py

This PR gives the `pb validate` CLI command the ability to perform multiple validations.

feat: allow CLI `pb validate` to perform multiple validations

---

docs/_quarto.yml
docs/user-guide/yaml-validation-workflows.qmd
pointblank/__init__.py
pointblank/yaml.py
tests/test_yaml.py

This PR introduces new YAML-related functionality and updates the documentation to reflect these additions.

feat: basic YAML config for validation workflow

---

pointblank/_interrogation.py
pointblank/_utils.py
pointblank/validate.py
tests/test_validate.py

This PR reduces code branching by routing Ibis tables through Narwhals instead of maintaining separate Ibis-specific code paths. This unifies DataFrame processing across all supported backends (Pandas, Polars, Spark, and Ibis).
Fixes: https://github.com/posit-dev/pointblank/issues/193

feat: process Ibis tables using Narwhals

---

.gitignore
docs/user-guide/thresholds.qmd
pointblank/_interrogation.py
pointblank/validate.py
pointblank/yaml.py
pyproject.toml
tests/test__interrogation.py
tests/test__utils.py
tests/test_segments.py
tests/test_validate.py
tests/test_yaml.py

This PR is focused on adding more testing of YAML validation workflows and generally refactoring the existing tests.

ci: add and reorganize tests

---

docs/user-guide/mcp-quick-start.qmd
pointblank_mcp_server/pointblank_server.py
tests/test_mcp_server.py

This pull request updates the Pointblank MCP code, adding a few more tools and fixing various issues encountered during tests. The MCP server tests are also updated and refined here. The docs expand and clarify the quick start workflow, supported features, and troubleshooting steps (making it easier for users to get started).

fix: MCP server issues

---

pointblank/column.py
pointblank/datascan.py
pointblank/validate.py
pointblank_mcp_server/pointblank_server.py
pyproject.toml
tests/test_datascan.py
tests/test_segments.py
tests/test_validate.py

This PR addresses a recent test failure encountered in CI (due to a Polars update) and fixes numerous warnings emitted from the tests. It also introduces improvements to segment handling for Polars DataFrames and updates dependency requirements.

ci: fix all CI test failures and warnings

---

pointblank/validate.py
tests/test_validate.py

This adds more tests for the `validate.py` file.

ci: add more tests for `validate.py`

---

pointblank/yaml.py
tests/test_yaml.py

This adds more tests for the `yaml.py` file.

ci: add more tests for `yaml.py` 

---

pointblank/cli.py
tests/test_cli.py

This PR adds a few tests for the cli.py file.

ci: add tests for cli.py
